### ISSUE TITLE
Add ability to turn off OIDC / Proxy functionality wholesale.

### ISSUE THREAD

**Issue by allandegnan** [keycloak/keycloak-gatekeeper#197]
In order to cut down the amount of different software we use, consider allowing simply using keycloak-proxy an a TLS reverse proxy where we can disable keycloak / oidc functionality.  

This will allow us to put it in front of services that don't actually need auth, the motivation of doing this is just so we can consistently use this proxy and kill of the nginx proxy.

**Comment by abstractj** [comment]
Hi @allandegnan unfortunately this out of scope and we don't have any plans do add it. The goal of keycloak-gatekeeper is to support Keycloak.

I'm closing this for now. But if in the future you see any other improvements or bugs, please open a Jira (https://issues.jboss.org/browse/KEYCLOAK)
