### ISSUE TITLE
Support Casbin as the authorization module

### ISSUE THREAD

**Issue by hsluoyz** [keycloak/keycloak-gatekeeper#246]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current RBAC. I can make PR if needed. Let me know if there's any question:) Thanks.

This may solve the issue: https://github.com/gambol99/keycloak-proxy/issues/82

**Comment by gambol99** [comment]
Hi @hsluoyz ... yes, i've come across the the [casbin](https://github.com/casbin/casbin) project a few times and was thinking about using here, I've not yet had the time to really investigate it yet though ...

**Comment by hsluoyz** [comment]
Hi @gambol99 ,

You can get a rough image of Casbin at the README.md here: https://github.com/casbin/casbin

The model syntax is here: https://github.com/casbin/casbin/blob/master/Model.md

Please contact me at the [Gitter](https://gitter.im/casbin/lobby) if you have any questions or want to discuss with me:)

**Comment by abstractj** [comment]
@hsluoyz thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
