### ISSUE TITLE
Add support for service accounts

### ISSUE THREAD

**Issue by nl5887** [keycloak/keycloak-gatekeeper#250]
When the request contains an Authorization header, the credentials will be passed to keycloak as an service account. 

[https://keycloak.gitbooks.io/documentation/server_admin/topics/clients/oidc/service-accounts.html]()

**Comment by gambol99** [comment]
Hi @nl5887  ... can you give a little extra detail. Do you mean you want the proxy to login on behalf of the user passing a username / password?

**Comment by nl5887** [comment]
I was more thinking in this use case: we have several services writing to Elasticsearch. It would be great to give those services accounts within Keycloak, so Elasticsearch can login using basic authentication, where keycloak will exchange the credentials with a token.

**Comment by gambol99** [comment]
hi @nl5887 ... have you looked at [forward signing mode](https://github.com/gambol99/keycloak-proxy#forward-signing-proxy) as i think this covers what you need. You pass it the username/password creds and the proxy will manage the token login and renewal for you and any request passed though the proxy will be tagged with an authorization header. ... You could then have another proxy verifying the header on the other end

**Comment by abstractj** [comment]
@nl5887 thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
