### ISSUE TITLE
Multi-stage Dockerfile

### ISSUE THREAD

**Issue by jangaraj** [keycloak/keycloak-gatekeeper#252]
Hi Rohith,

Thanks for your project. 

Docker now supports [multi stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/), which is great feature for compilation. Could you add `Dockerfile_multistage` file into repo please? `MAINTAINER` is also deprecated. Minimalist example (~10MB image size):

```
LABEL Name=keycloak-proxy \
     maintainer="Rohith Jayawardene <gambol99@gmail.com>" \
     Release=https://github.com/gambol99/keycloak-proxy \
     Url=https://github.com/gambol99/keycloak-proxy \
     Help=https://github.com/gambol99/keycloak-proxy/issues

FROM golang:1.8 as build
RUN go get -d github.com/gambol99/keycloak-proxy \
  && cd /go/src/github.com/gambol99/keycloak-proxy \
  && make static

FROM ubuntu as cert
RUN apt-get update && apt-get install -y ca-certificates

FROM scratch
WORKDIR /
COPY --from=build /go/src/github.com/gambol99/keycloak-proxy/bin/keycloak-proxy /
COPY --from=cert /etc/ssl/certs /etc/ssl/certs

CMD ["/keycloak-proxy"]
```

**Comment by gambol99** [comment]
hi @jangaraj ... definitely something worth adding! .. By chance do you know if travis supports the version feature?

**Comment by jangaraj** [comment]
Yes, but probably you need to install latest `docker-ce` version first:
```
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
```
https://docs.travis-ci.com/user/docker/

**Comment by abstractj** [comment]
@jangaraj thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
