### ISSUE TITLE
The case of login being optional

### ISSUE THREAD

**Issue by dalu** [keycloak/keycloak-gatekeeper#270]
On a classic website you have a front page.
On this front page you have something like a "Welcome Firstname Lastname" or "Login or Register" if not logged in.

When defining resources that need to be guarded, to my knowledge, there is no possibility to say "login is optional".
```yaml
discovery-url: https://domain/auth/realms/testrealm
client-id: someid
client-secret: somesecret
listen: 127.0.0.1:8080
encryption_key: 1234567890123456
upstream-url: http://127.0.0.1:3000
secure-cookie: false
resources:
- uri: /doc*
  methods:
  - GET
  - POST
  - DELETE
```

This is a test program
```go
package main

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/SermoDigital/jose/jws"
)

func main() {
	h := &Handler{}
	http.ListenAndServe(":3000", h)
}

type Handler struct{}

func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		fmt.Fprintln(w, "GET")
		h.printXHeaders(w, r)
		j, err := jws.ParseFromHeader(r, jws.Unknown)
		if err != nil {
			fmt.Fprintln(w, err.Error())
			return
		}
		fmt.Fprintln(w, j.Payload())
		i, _ := j.Payload().(map[string]interface{})
		fmt.Fprintln(w, i["name"])
	case http.MethodPost:
		fmt.Fprintln(w, "POST")
		h.printXHeaders(w, r)
	case http.MethodDelete:
		fmt.Fprintln(w, "DELETE")
		h.printXHeaders(w, r)
	default:
		fmt.Fprintln(w, "NOT ALLOWED")

	}
}

func (h *Handler) printXHeaders(w http.ResponseWriter, r *http.Request) {
	for k, v := range r.Header {
		if strings.HasPrefix(k, "X-") {
			fmt.Fprintln(w, k, v)
		}
	}
}
```

with the above program if you *are* logged in and hit `/` uri the result is

```
GET
X-Forwarded-For [127.0.0.1]
X-Forwarded-Host [127.0.0.1:3000]
X-Forwarded-Proto []
no token present in request
```

So I'm suggesting to have a configurable means to pass the token regardless of an endpoint or endpoint prefix being protected or not.

If you already can do that then sorry for bothering.

**Comment by jangaraj** [comment]
Theoretical workaround:
"Welcome Firstname Lastname" = (index) page served by your app
"Login or Register" = customized sign in page served by keycloak-proxy; config:
```
signin-page: /templates/sign_in.html.tmpl
resources:
- uri: /*
```
You can customize that sign_in template - you can also create login form there, which will use `/oauth/login` endpoint - a relay endpoint to login via *grant_type=password* i.e. POST */oauth/login* form values are *username=USERNAME&password=PASSWORD* (must be enabled)

**Comment by dalu** [comment]
Hmm yeah maybe but there's more than just "Login or Register". There's probably a navbar, one or other menu, tags, maybe content and so on.
And it wouldn't be just one page it would be multiple.
"Since you're not logged in I'm showing you only a portion of the content, but I'm giving you the opportunity to register an account, you can even use google,facebook,twitter, just click here. But you're still able to view the page without being logged in, you just can't see certain features" classic websites, not a SPA, not isomorphic.

I propose:

```yaml
resources:
- uri: /
  optional: true # default false
```
or call it `auth-optional` or `optional-auth`, altough I believe `optional` is sufficient.


-------------------
while I'm at it https://github.com/gambol99/keycloak-proxy/blob/master/config.go#L30
`time.Duration(720) * time.Hour` isn't necessary. 720 * time.Hour is also of type time.Duration. Only time.Hour without being multiplied is not of type time.Duration.

**Comment by dalu** [comment]
Actually now that I changed some code in the fork, that `white-listed` should be the new `optional`.
I don't know if it make sense to completely whitelist a resource, you'd still want to know if the client is authenticated.
Why this whitelist in the first place?

**Comment by dalu** [comment]
And now I'm thinking,
why not call this `passthrough`
with options:
- none (default)
- whitelist
- optional

**Comment by dalu** [comment]
I don't know what purpose this (proxy) fulfills.

Let's take the following scenario:
Angular App
API protected with keycloak-proxy

Angular App uses implicit flow with a different client_id and no secret, because [openid-connect spec says so](http://openid.net/specs/openid-connect-core-1_0.html#Authentication).
keycloak-proxy uses different client_id and client_secret,
now you initiate the implicit flow in the angular client and you receive a token and good stuff, however you can not use this token because the `aud` audience is a different client_id than that from the keycloak-proxy

This should probably be a new issue, support multiple client ids or add support for implicit flow client id additionally to authorization code or hybrid flow

And you probably think, "why have an optional login? you can just use some middleware and optionally pass even if no id_token or access_token exists". Well yes, but separation of concerns.

btw I did try to write this but got stuck in your handling logic.

**Comment by justjanne** [comment]
I’m having this exact issue right now.

I’d be willing to contribute to this project to implement a feature where, even if the page is whitelisted, if the user is logged in, the logged in headers are sent, if the maintainers would accept that. (timeframe: within of the next few days)

**Comment by dalu** [comment]
I was just thinking about this and how I'd solve it with some middleware and why this doesn't do it.
If you really manage to pull it off, hats off. Godsent.

**Comment by justjanne** [comment]
I’ve implemented this over here: https://git.kuschku.de/justJanne/keycloak-proxy/commit/fe369389540a9e02e7ceb521082799d76573476b

You can take that diff and use it in your own version, if you wish, I’m running it right now.

**Comment by dalu** [comment]
Doesn't seem to work
keycloak.yml
```yaml
discovery-url: https://connect.icod.de/auth/realms/i-lov.eu
client-id: web-client
listen: 127.0.0.1:8080
encryption-key: rjosjNhw0NBRSw4LLo5A88AN8uOkfget
upstream-url: unix:///tmp/dating.socket
secure-cookie: false
no-redirects: true
verbose: true
cors-origins: ['*']
cors-methods: [GET, POST, PUT, OPTIONS, DELETE]
cors-headers: ['*']
resources:
- uri: /api/v1/*
  methods:
  - POST
  - PUT
  - DELETE
- uri: /api/v1/*
  methods:
  - GET
  white-listed: true
```

```
X-Forwarded-For [127.0.0.1]
X-Forwarded-Host [domain-sock]
X-Forwarded-Proto []
[GIN] 2018/03/19 - 13:54:41 | 200 |     518.047µs |       127.0.0.1 | GET      /api/v1/profile/
X-Forwarded-Proto [http]
X-Forwarded-For [192.168.1.4 192.168.1.4]
X-Forwarded-Host [domain-sock]
X-Real-Ip [192.168.1.4]
X-Forwarded-Proto [http]
X-Forwarded-Host [domain-sock]
X-Forwarded-For [192.168.1.4 192.168.1.4]
X-Real-Ip [192.168.1.4]
[GIN] 2018/03/19 - 13:55:19 | 200 |     358.174µs |     192.168.1.4 | GET      /api/v1/profile/by_owner/44f022d4-4a0d-4714-b73d-07e87b913501
[GIN] 2018/03/19 - 13:55:19 | 200 |     476.461µs |     192.168.1.4 | GET      /api/v1/profile/by_owner/44f022d4-4a0d-4714-b73d-07e87b913501
X-Forwarded-For [192.168.1.4 192.168.1.4]
X-Forwarded-Proto [http]
X-Forwarded-Host [domain-sock]
X-Real-Ip [192.168.1.4]
[GIN] 2018/03/19 - 13:55:29 | 200 |     332.939µs |     192.168.1.4 | GET      /api/v1/profile/by_username/dalu
X-Forwarded-Proto [http]
X-Forwarded-Host [domain-sock]
X-Forwarded-For [192.168.1.4 192.168.1.4]
X-Real-Ip [192.168.1.4]
[GIN] 2018/03/19 - 13:55:35 | 200 |     307.807µs |     192.168.1.4 | GET      /api/v1/profile/by_owner/44f022d4-4a0d-4714-b73d-07e87b913501
X-Forwarded-For [192.168.1.4 192.168.1.4]
X-Forwarded-Host [domain-sock]
X-Forwarded-Proto [http]
X-Real-Ip [192.168.1.4]
[GIN] 2018/03/19 - 13:55:53 | 200 |     326.441µs |     192.168.1.4 | GET      /api/v1/profile/by_owner/44f022d4-4a0d-4714-b73d-07e87b913501
```

note: debug output comes before the request is logged

ahead of each handler is essentially what I described in the initial post
```go
	for k, v := range ctx.Request.Header {
		if strings.HasPrefix(k, "X-") {
			fmt.Println(k, v)
		}
	}
```
e.g.
```go
func (h *Handler) ProfileFindByOwner(ctx *gin.Context) {
	for k, v := range ctx.Request.Header {
		if strings.HasPrefix(k, "X-") {
			fmt.Println(k, v)
		}
	}
```

**Comment by pjeby** [comment]
FYI, I've cleaned up the patch from @justjanne so that it works with master as PR #335.  With that PR, it's possible to whitelist everything and let an app handle its own security, doing explicit logins only via `oauth/authorize`.

**Comment by dalu** [comment]
@pjeby Have you tested if it works? (ref: my above comment with whitelist for GET but not POST PUT DELETE) I'm currently in the middle of bringing an idea to life and can't lose momentum.

**Comment by pjeby** [comment]
It works for my use case, which is making it easier to integrate with an older app that can handle authentication via headers but can't do OIDC.  So the entire app is completely whitelisted, it just links to /oauth/authorize and oauth/logout for login and logout respectively, with everything else handled via the headers.  I haven't tried whitelisting some methods but not others.

**Comment by dalu** [comment]
@pjeby 
What should have happened:

The user was logged in, so headers about his claims should've been sent, since he was logged in.
As you can see from the configuration
```yaml
resources:
- uri: /api/v1/*
  methods:
  - POST
  - PUT
  - DELETE
- uri: /api/v1/*
  methods:
  - GET
  white-listed: true
```

as you can see in the log, the 1st entry
```
X-Forwarded-For [127.0.0.1]
X-Forwarded-Host [domain-sock]
X-Forwarded-Proto []
[GIN] 2018/03/19 - 13:54:41 | 200 |     518.047µs |       127.0.0.1 | GET      /api/v1/profile/
```

And I've added what the endpoint does:
```go
func (h *Handler) ProfileFindByOwner(ctx *gin.Context) {
	for k, v := range ctx.Request.Header {
		if strings.HasPrefix(k, "X-") {
			fmt.Println(k, v)
		}
	}
```

When a user is logged in/authenticated headers are sent with information about him.
They always have a X- prefix
So this endpoint prints any header with a X- prefix to console.

Right.
Now look at the log again.
It prints
```
X-Forwarded-For [127.0.0.1]
X-Forwarded-Host [domain-sock]
X-Forwarded-Proto []
```
then gin's log entry is printed about what method was used, which path etc.
```
[GIN] 2018/03/19 - 13:54:41 | 200 |     518.047µs |       127.0.0.1 | GET      /api/v1/profile/
```

So when doing this request the user, me, was logged in and the endpoint and GET method was configured to allow the "new whitelisted".
```yaml
- uri: /api/v1/*
  methods:
  - GET
  white-listed: true
```
however
the "doesn't work" part:
No openid-connect headers by keycloak-proxy were sent.

**Comment by dalu** [comment]
you have a number of endpoints and methods to access them.

So you configure the URIs and the METHODS.

```yaml
- uri: /posts/*
  methods:
  - PUT
  - DELETE
- uri: /posts/*
  methods:
  - GET
  - POST
  white-listed: true
```

so that means that anything with a `/posts/` prefix that uses the methods `GET` or `POST` should be white-listed. And @justjanne's solution "does not work" in that way that is doesn't send headers when "white-listed". That's the whole deal about this whole issue.
You have endpoints and methods and want certain methods to pass visitors, but also add headers when a visitor is a member/logged in.

I don't know how I can explain it any other way so it's more clear.

**Comment by pjeby** [comment]
And the part that's confusing to me is that I'm actually using it in production and it does in fact send the auth headers through.  Granted, I am not listing specific methods, just whitelisting everything, like this (copied directly from my working config):

```yaml
resources:
  - uri: /*
    white-listed: yes
```

With this configuration, the version from my PR does send auth headers through to the app, whether someone is logged in or not.  So, please try testing your setup with this resource configuration first, to verify that your log shows the X headers you're looking for.  If they show up with this configuration, that validates your log is logging what you think it does, and you can then start adding back your actual configuration to see at what point it breaks. 

Is the issue with listing specific methods?  With having two configs for the same path?  With having the blacklist path before the whitelist path?  There are quite a few possibilities for why your configuration might not be working, so narrowing it down to the most minimal breaking configuration would be helpful for anyone investigating the issue on the code side.  (Especially since the problem may not actually be in the patch, but in an interaction with some other aspect of how keycloak-proxy works.)

**Comment by dalu** [comment]
Well if this tool, keycloak-proxy worked a certain way before, as described above
endpoint & methods = pass or no pass
then assuming a modification was done
it has to be working the same way it did previously with the exception of headers being sent on "pass" endpoint & methods combination.

So
pre modification:
endpoint+methods = pass anyway, no pass without authN
after modification:
endpoint+methods = pass with headers, no pass without authN

`/*` seems to be a special case again because #378

At this point I'm under the impression to just ditch the whole mess and start fresh. When someone doesn't know what `strings.Trim` does and uses it to actually trim string prefixes my confidence in the whole project is very low. Especially now that it's meant to act as a firewall between the endpoints and the clients. Then goes on and ignores pull requests I get the feeling it's not even desired that anyone fixes things in this repo.
But maybe I've just having a streak of bad experiences in the place I'm at right now and that clouds my judgement.

```go
package main

import (
	"fmt"
	"log"
	"strings"
	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()

	api := r.Group("/api")
	v1 := api.Group("/v1")
	endpoints := v1.Group("/endpoints")

	endpoints.GET("/", TestHandler)
	endpoints.POST("/", TestHandler)
	endpoints.PUT("/", TestHandler)
	endpoints.DELETE("/", TestHandler)
	endpoints.HEAD("/", TestHandler)
	endpoints.OPTIONS("/", TestHandler)
	endpoints.PATCH("/", TestHandler)
	log.Fatal(r.Run(":8080"))
}

func TestHandler(cx *gin.Context) {
	for k, v := range cx.Request.Header {
		if strings.HasPrefix(k, "X-") {
			fmt.Println(k, v)
		}
	}
}
```

Here's a test program you can use to stick behind your version of keycloak-proxy.
If you tell me how to acquire your version, by posting the commands I have to run, I'll be happy to run a test.

**Comment by pjeby** [comment]
```shell
git clone https://github.com/pjeby/keycloak-proxy $GOPATH/src/github.com/gambol99/keycloak-proxy
cd $GOPATH/src/github.com/gambol99/keycloak-proxy
git checkout optional-login
glide install
make build
```

After that, you should have a built version in `./bin`.

**Comment by abstractj** [comment]
@dalu thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.

**Comment by stianst** [comment]
In the Keycloak project we have many repositories and need something more advanced than GitHub issues. We can not actively monitor many sources of issues. So we need to use JIRA.

We could have create the JIRAs for the GitHub issues, but we would then not have the original reporter on the issue which would not be correct.

Please elaborate on what is to restrictive about our policy. If you are simply referring to the fact that we will use JIRA and not GitHub issues, that is just the way it is. Please consider this from our perspective that have to manage a large community spread across multiple repositories and a very large amount of requests.

With regards to contributions if you have already contributed to this project you have done so under the terms of Apache License 2.0 and as such you can't withdraw contributions. At the same time your are free to create your own fork where you manage issues with GitHub issues.
