### ISSUE TITLE
Compromised tokens / support for revocation policy

### ISSUE THREAD

**Issue by leoluk** [keycloak/keycloak-gatekeeper#333]
How would I force a logout across multiple keycloak-proxy instances if a user's account / tokens were compromised?

Keycloak seems to handle this by using revocation policies: https://www.keycloak.org/docs/2.5/server_admin/topics/sessions/revocation.html

**Comment by gambol99** [comment]
hi @leoluk .. at the moment this isn't supported .. Its not entirely clear if this just revokes the session you have with keycloak or provides a mechanism for an RP to revoke an access token

**Comment by leoluk** [comment]
It revokes both the internal Keycloak SSO session as well as any access tokens handed out to users, by pushing a "all tokens before now are invalid" revocation policy to any registered clients/RPs.

**Comment by gambol99** [comment]
Do you have a link to the docs or code of how they've implemented this RP side? .. would be a cool feature to add ..

**Comment by gambol99** [comment]
OK .. i can see "Admin URL" in the client configuration .. i'm guessing you setup a endpoint to receive a verifiable payload from the keycloak server. ... hmmm .. i'm not sure that could work with stateless client though ..

**Comment by leoluk** [comment]
Here's the Java implementation:

https://github.com/keycloak/keycloak/blob/a63bb44ba2d1becd257aaf6ddeed15222a774bab/adapters/oidc/adapter-core/src/main/java/org/keycloak/adapters/PreAuthActionsHandler.java#L169

The interesting ones are `K_PUSH_NOT_BEFORE` (revocation policy) and `K_LOGOUT` (backchannel logout).

Obviously, making it stateless is hard, the value has to be stored somewhere. Maybe it's possible to query the current revocation policy from Keycloak at startup?

**Comment by abstractj** [comment]
@leoluk thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
