### ISSUE TITLE
Support of more than one authentication methods in Token Endpoint is contradicting with OAuth2 Specification

### ISSUE THREAD

**Issue by shyamz-22** [keycloak/keycloak-gatekeeper#336]
Taking into account the following line from the Readme

> Although technically the service has no dependency on Keycloak itself and would quite happily work with any OpenID provider.

I would like to understand why multiple client authentication methods (both `client_secret_basic` and `client_secret_post`) are supported in Token endpoint, as this may result in an error if an Identity provider does not support more than one authentication method in a given Token endpoint request

According to Specification

Token endpoint client authentication https://tools.ietf.org/html/rfc6749#section-3.2.1

> Confidential clients or other clients issued client credentials `MUST` authenticate with the authorization server as described in `Section 2.3` when making requests to the token endpoint.

For client authentication https://tools.ietf.org/html/rfc6749#section-2.3
> The client `MUST NOT` use more than one authentication method in each request.

Definition of `MUST NOT` as per spec https://tools.ietf.org/html/rfc2119
> This phrase, or the phrase “SHALL NOT”, mean that the definition is an absolute prohibition of the specification.

IMHO `client_secret_basic` must be the default option for token authentication and `client_secret_post` can be a configurable parameter for clients that cannot support Basic authentication.

**Comment by jangaraj** [comment]
It is coming from the upstream project: https://github.com/coreos/go-oidc/blob/8ae400b75540a4f57ec549a89b3e9d994c636f2a/oauth2/oauth2.go#L260

It was already part of PR: https://github.com/gambol99/go-oidc/pull/2, but we need to create better PR.
@janiwe and me have the same problem and we are trying to find the best solution

**Comment by abstractj** [comment]
@shyamz-22 @jangaraj thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
