### ISSUE TITLE
CoreOS OpenID Deps

### ISSUE THREAD

**Issue by gambol99** [keycloak/keycloak-gatekeeper#351]
Need to move off the current fork [github.com/gambol99/go-oidc](https://github.com/gambol99/go-oidc) and back onto the main [github.com/coreos/go-oidc](https://github.com/coreos/go-oidc).

**Comment by abstractj** [comment]
@gambol99 there are few steps we have to take before doing that. There are 2 ways:

## 1st approach

* Move to **coreos/go-oidc v1*: if we want to move to this repo/version it's fairly simple, we "just" need to get rid of *SkipClientIDCheck* and we are all set. I have a working copy locally here. The downside is to remove a feature which people may want to use.

## 2nd approach

* Migrate to **coreos/go-oidc v2**: this would be my preferred choice if you ask me, but just switching to *v2* we lose the following packages *jose*, *oidc* and *oauth*. So I see some steps before move to v2:

- [ ] Move from go-oidc/oauth to golang/x/oauth2
- [ ] Move from go-oidc/jose to square/go-jose.v2 

These packages are the same used by coreos guys, but doing the complete migration requires a ton of work, once it breaks completely the API compatibility.

## A middle ground

This is the approach which I'm actually trying:
* Moved the codebase to coreos/go-oidc.v1
* Added coreos/go-oidc.v2 and I'm trying to find a way to create a wrapper for *SkipClientIDCheck*, in this way we don't lose this functionality.

My goal is to slowly migrate to v2. Does anything of this make sense to you? Which approach do you think makes more sense?

**Comment by gambol99** [comment]
hi @abstractj .. the middle ground sounds like the right way forward to me .. Have you started work on this already? .. or do you want me to take a look at it ..

**Comment by abstractj** [comment]
> hi @abstractj .. the middle ground sounds like the right way forward to me .. Have you started work on this already? .. or do you want me to take a look at it ..

@gambol99 After chatting with the team, we reached the consensus that the 2nd approach would be better for us. Even if it takes more time, it pays off in the long run. So I started to look at this. But if you think is a bad idea, please let me know.

We created the following Jira to track this: [](https://issues.jboss.org/browse/KEYCLOAK-7265). If you would like to split the work, have suggestions or ideas on how to approach this. You are more than welcome.

I will certainly need your review after finish this, to make sure that I didn't mess things up.

**Comment by abstractj** [comment]
@gambol99 I'm closing this for now. Let's move the discussion to Jiras.
