### ISSUE TITLE
Help with OneLogin integration

### ISSUE THREAD

**Issue by balan2010** [keycloak/keycloak-gatekeeper#384]
HI,

I am trying to get keycloak-proxy to work with onelogin openid connect. I was following this article 

https://itnext.io/protect-kubernetes-dashboard-with-openid-connect-104b9e75e39c

Authentication itself works as below

`1.5298344134825583e+09	debug	keycloak-proxy/session.go:51	found the user identity	{"id": "40509719", "name": "balan2010", "email": "myemail@gmail.com", "roles": ""}
1.5298344134827087e+09	debug	keycloak-proxy/middleware.go:312	access permitted to resource	{"access": "permitted", "email": "myemail@gmail.com", "expires": 6558.517291762, "resource": "/*"}`

but then on dashboard could see below warning and couldn't view any in objects in any namespace 
 
`" pods is forbidden: User "https://openid-connect.onelogin.com/oidc#40509719" cannot list pods in the namespace "default"`

      - image: quay.io/gambol99/keycloak-proxy:v2.1.1
        name: kubernetes-dashboard-proxy
        args:
          - --listen=0.0.0.0:3000
          - --discovery-url=https://openid-connect.onelogin.com/oidc
          - --client-id=4f510820-58ab-0136-d6a6-0a462d4f063a129509
          - --client secret=xyz
          - --redirection-url=https://s-zip-k8s-dashboard.dev.zip.co
          - --enable-refresh-tokens=true
          - --encryption-key=Fxyxyast
          - --upstream-url=http://kubernetes-dashboard.kube-system
          - --resources=uri=/*`

RBAC config

` kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-admin-group
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: /addons `

Any idea on what I am doing wrong here

**Comment by gambol99** [comment]
hi @balan2010 ... did you find the answer to this? ...

**Comment by fkpwolf** [comment]
forgot to do "user mapper" step?

**Comment by balan2010** [comment]
@gambol99 no I haven't found the solution.  my focus got shifted to something else. Will get back to this soon

**Comment by balan2010** [comment]
@fkpwolf I haven't checked that, thanks for the pointer

**Comment by abstractj** [comment]
@balan2010 thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
