### ISSUE TITLE
Invalid_client when connecting to PingIdentity 

### ISSUE THREAD

**Issue by icklers** [keycloak/keycloak-gatekeeper#416]
Hi guys,

I have a problem when I want to connect to my IDP, which is in this case PingIdentity. I'm deploying on Azure Kubernetes Service.

I'm starting the pod with following options:
````
        - --listen=0.0.0.0:3000
        - --resources=uri=/*
        - --upstream-url=http://<SERVICENAME>.default.svc.cluster.local
        - --verbose
        - --enable-logging # enable HTTP logging
        - --discovery-url=https://<PingIdentityFQDN>/.well-known/openid-configuration
        - --client-id=<CLIENTID>
        - --client-secret=<CLIENT_SECRET>
````
The error message dropped by keycloak-proxy is:

```
> 1.5361615280745962e+09  error   keycloak-proxy/middleware.go:108        no session found in request, redirecting for authorization      {"error": "authentication session not found"}
> 1.536161528103292e+09   debug   keycloak-proxy/handlers.go:81   incoming authorization request from client address
> {"access_type": "", "auth_url": "https://<PingIdentityFQDN>/as/authorization.oauth2?client_id=<CLIENTID>&redirect_uri=https%3A%2F%2F<FQDN>%2Foauth%2Fcallback&response_type=code&scope=openid+email+profile&state=Lw%3D%3D", "client_ip": "10.244.0.10:54000"}
> 1.5361615367945359e+09  error   keycloak-proxy/handlers.go:121  unable to exchange code for access token        {"error": "invalid_client: The client MUST NOT use more than one authentication method in each request."}
```

It seems as keycloak-proxy sends two authentication methods. This is not supported in PingIdentity, which follows the RFC very strictly.

I found this issue (https://github.com/postmanlabs/postman-app-support/issues/3357) which resolves it by unchecking a box when filling in the credentials ("Request access token locally". 
> When it's checked the App makes the second request using both authentication methods
> When it's unchecked our server is used which only sends the credentials in the body

Is there any option in keycloak-proxy to limit the request on one authentication method?
`--enable-authorization-header=false` did not work, and it seems it's limited if you use the proxying function.

Thanks in advance, I appreciate this project very much!

Regards,

Sebastian
Ps. Google's OpenID implementation works fine :)

**Comment by icklers** [comment]
Thanks for the information, @jangaraj 

Is the develop branch usable? I saw some oidc2 implementation there.

Thanks in advance?
Sebastian

**Comment by jangaraj** [comment]
I didn't test `develop` branch with `coreos/go-oidc v2`. I'll be happy if you can test it and report your results.
