### ISSUE TITLE
Nginx -> keycloak-proxy -> keycloak ?

### ISSUE THREAD

**Issue by lukasmrtvy** [keycloak/keycloak-gatekeeper#418]
Have anyone experience with nginx (auth_request) and keycloak-proxy? 
This is another layer in front of keycloak-proxy. Problems are 302 errors. 

Maybe if I change authentication flow in keycloak https://stackoverflow.com/questions/51925423/keycloak-how-to-auto-redirect-keycloak-user-to-okta-sso-page-instead-of-clickin/52176780#52176780, I can use internal directive on /oauth2 and hide even keycloak behind proxy to do this transparently.

```
  location = /oauth2/ {
    proxy_pass       http://keycloak-proxy/oauth2/;
    proxy_redirect              default;

    proxy_set_header   Host             $host;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Original-URI $request_uri;

    proxy_set_header Content-Length   "";
    proxy_pass_request_body           off;

    proxy_intercept_errors on;
    error_page 302 = @handle_redirect;
  }

  location @handle_redirect {
    set $saved_redirect_location '$upstream_http_location';
    proxy_pass $saved_redirect_location; 
  }

  location / {
      auth_request /oauth2/; 
      error_page 401 = /oauth2/;
      proxy_pass http://target_host/;
  }
```

**Comment by abstractj** [comment]
@lukasmrtvy thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
