### ISSUE TITLE
Basic authentication middleware?

### ISSUE THREAD

**Issue by bogdanpetrea** [keycloak/keycloak-gatekeeper#425]
Hi,

I want to be able to use basic auth to obtain authorization from an oath service, as in the client offers the user and password through basic auth, rather than through a login page.

I already tried implementing a [basic authentication middleware](https://github.com/presslabs/keycloak-gatekeeper/pull/1/files) and it seems to be working for the most part, but we should probably discuss the feature here anyway.

**Comment by abstractj** [comment]
Hi @bogdanpetrea unfortunately basic authentication is out of scope and we don't have any plans do add it. Still, the code is open source so you can tweak it to your own needs.

I'm closing this for now. But if in the future you see any other improvements or bugs, please open a Jira (https://issues.jboss.org/browse/KEYCLOAK)

**Comment by calind** [comment]
Hi!

Would you care to reconsider closing this?

The use case is as follows: the proxy sits in front of a git server; users should be able to clone their repos using their user/password sent using basic auth.

I see that there's as `POST /oauth/login` endpoint which allows logging in users using user/password combo (by using `password` as `grant_type`). Is there a specific reason for not allowing this trough HTTP Basic auth?

Thanks!
