### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by navi86** [keycloak/keycloak-gatekeeper#426]
Hello,
Docker build doesn't work, due to the fact that there is no folder bin.
repository docker.io/jboss/keycloak/keycloak-gatekeeper:latest
doesn't exist.
How to download docker image ?

**Comment by jangaraj** [comment]
https://github.com/keycloak/keycloak-gatekeeper/issues/422

**Comment by abstractj** [comment]
@navi86 GH issues is no longer being used to track gatekeeper issues and soon it will be closed. For any bugs or feature request, please file a Jira. For the Docker image the work is being tracked here https://issues.jboss.org/browse/KEYCLOAK-7177 and @jangaraj has been kindly helping review this PR https://github.com/jboss-dockerfiles/keycloak/pull/154.

I'm closing this for now, but feel free to comment on that Jira if you have any questions.
Thank you.
