### ISSUE TITLE
Login form additional to login redirect.

### ISSUE THREAD

**Issue by vizapata** [keycloak/keycloak-gatekeeper#534]
Should the keycloak gatekeeper have the ability have its own login interface and manage the login flow? I mean, Keycloak Gatekeepr can get the token from the auth server with a login form instead of redirecting to the authorization server? 

This scenario is useful when we want to authenticate users but keep private the keycloak authorization server.

**Comment by jangaraj** [comment]
This should be already possible. Try to play with `enable-login-handler` (maybe another config options as well). Of course you will lost SSO functionality with this setup and used OIDC client must have `Direct Access Grants` enabled.

**Comment by vizapata** [comment]
Yes, it can be made with the login handler and the custom sign-in template.

Thank you @jangaraj

**Comment by jangaraj** [comment]
Could you paste example configuration for this configuration, please? Just for the record, please.
