### ISSUE TITLE
Keycloak auhtorization service

### ISSUE THREAD

**Issue by p53** [keycloak/keycloak-gatekeeper#542]
Hi, do you consider to implement use of keycloak authorization services, keycloak includes Policy decision points, so you can have central policy management and you don't have to specify this in text per gatekeeper...

**Comment by scandinave** [comment]
For me, It's already implemented. Try to not defined any policy inside the gatekeeper conf and enable authorization inside your client. That should work.

**Comment by stianst** [comment]
Gatekeeper doesn't have support for an external PDP today. Would be good to have that.

@scandinave not sure I quite understand your comment. Do you mean that the client can invoke the PDP itself? If so that's not the same as having support for it in Gatekeeper itself.

**Comment by scandinave** [comment]
I see this is my gatekeeper log when i launch it without any policy in the conf file 

`  protecting resource     {"resource": "uri: /*, methods: DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT,TRACE, required: authentication only"}`

` access permitted to resource    {"access": "permitted", "email": "foo@bar.baz", "expires": 297.24347729, "resource": "/*"}
`

This is the policy defined in my client inside keycloak. So it seems to use it to check if the request should be authorize or not.

**Comment by stianst** [comment]
Not sure what you mean with "This is the policy defined in my client inside the keycloak authorization tab". That just says that only authentication required, so anyone that is authenticated can access your resource. Gatekeeper does not invoke/support the Keycloak authorization services.

**Comment by scandinave** [comment]
Ok. So this is definitely a needed feature. :)

**Comment by p53** [comment]
would be enough making call to 
```curl -X POST \
  http://${host}:${port}/auth/realms/${realm}/protocol/openid-connect/token \
  -H "Authorization: Bearer ${access_token}" \
  --data "grant_type=urn:ietf:params:oauth:grant-type:uma-ticket" \
  --data "audience={resource_server_client_id}"```

and checking if there is resource URI#SCOPE?? Where scope/s would be configurable in gatekeeper config, e.g. automatically fill for scope attributes  from HTTP request like METHOD or other...

**Comment by abstractj** [comment]
Superseded by #546. We're going to plan the implementation around authorization services.
