### ISSUE TITLE
Option to add upstream headers on white-listed resources?

### ISSUE THREAD

**Issue by mlsen** [keycloak/keycloak-gatekeeper#601]
Hello, quick question!

Is there a way to add the upstream headers (the ones extracted from the token, X-Auth-*) on white-listed routes? So that if there's a token present the headers will be added, otherwise they'll just be omitted? Would be pretty handy imo.

I have tried the "white-listed: true" option, the request goes through as expected, but no headers unfortunately. The other thing I tried was not requiring any roles, but obviously the request doesn't go through without a token this way.

Thanks!

**Comment by abstractj** [comment]
GitHub issues is used exclusively for bug reports or feature requests. For questions, please use the mailing list.
